name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa todos os dias à meia-noite (UTC)
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante que todas as branches sejam baixadas

      - name: Gerar animação de cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Fazer commit e push da animação
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Atualizar animação da cobrinha" || echo "Nenhuma alteração para commit"
          git push origin main
